[package]
name = "ile"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Integrated Language for Extensions: An embedded scripting language with tight Rust bindings"
keywords = ["language"]
readme = "crate_readme.md"
repository = "https://github.com/left-alert-chaos/ile"
homepage = "https://github.com/left-alert-chaos/ile"
exclude = [
	"ile.png",
	"docs",
	"examples",
	"README.md",
]
